services:
  api:
    build: .
    container_name: openfabric-api
    command: npx tsx src/server.ts
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - mock
    environment:
      - POSTING_URL=http://mock:4000

  worker:
    build: .
    container_name: openfabric-worker
    command: npx tsx src/workerMain.ts
    volumes:
      - .:/app
    depends_on:
      - redis
      - mock


  redis:
    image: redis:7-alpine
    container_name: redis-db
    ports:
      - "6379:6379"

  mock:
    build:
      context: .
      dockerfile: Dockerfile.mock
    container_name: mock-posting
    ports:
      - "4000:8080"
